### ISSUE TITLE
Unneccesary variable assignment

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#37]
https://github.com/PacktPublishing/Laminas-Web-Development/blob/3896852da56e3d14154ccc634ca22461b384146c/chapter11/whatstore/module/Store/src/Module.php#L12

return include __DIR__ . '/../config/module.config.php';

**Comment by fgsl** [comment]
It is good. But I don't talk about it in the book.

It is better to change the source: https://github.com/laminas/laminas-mvc-skeleton/pull/59

**Comment by tyrsson** [comment]
I agree. I hope it is addressed in the next release. Since there are many changes that need to be accomplished before the next release in prep for 8.1 I may open a pull request.
