### ISSUE TITLE
Duplicate method

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#38]
https://github.com/PacktPublishing/Laminas-Web-Development/blob/3896852da56e3d14154ccc634ca22461b384146c/chapter11/whatstore/module/Store/src/Model/Customer.php#L33

This is why I suggested to move this to a filter. The custom filter can then be attached like any other filter and can be applied to any entity that implements the InputAwareInterface or InputProviderInterface. Keeps the code DRY.

**Comment by fgsl** [comment]
Very good suggestion.

I understand that if you can solve the problem immediately, you must do it.

However, this is not the planned moment to talk about filter customization. This is approached in Chapter 13.

**Comment by tyrsson** [comment]
Gotcha,. I'm trying not to read ahead because I feel it might skew my perception of the text as it stands so please bare with me if I suggest changes that are addressed later.

**Comment by fgsl** [comment]
Opportunity was found.
