### ISSUE TITLE
Why is login split between two modules?

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#39]
https://github.com/PacktPublishing/Laminas-Web-Development/blob/3896852da56e3d14154ccc634ca22461b384146c/chapter11/whatstore/module/Store/src/Controller/CustomerController.php#L34

Why is login split between two different modules? I would think that a single login would be provided and then the user would be redirected depending on "who or what" they are within the application. This seems redundant.

**Comment by fgsl** [comment]
Yes, it makes sense completely.

In fact, there is another intention with two logins. They generate a problem that is solved in Chapter 12.

But the question of one single login point could be implemented in Chapter 12 too. I will think about when to finish the plan for rewriting the chapters.

The mentioned problem is related to session. There is a story in Chapter 12, not so good as you told in issue #35.

Talking about it, oh, my God, I LOVED YOUR STORY ! It needs to be added, as well as session invalidation.

**Comment by tyrsson** [comment]
I will read ahead then and look into the mentioned problem as I have very recent deep dive knowledge of how Laminas Session and its usage can be problematic in applications such as these. Matter of fact I can probably provide the code to fix it (since I most likely already have it written lol). Can I open a pull request against this repo?

**Comment by fgsl** [comment]
> I will read ahead then and look into the mentioned problem as I have very recent deep dive knowledge of how Laminas Session and its usage can be problematic in applications such as these. Matter of fact I can probably provide the code to fix it (since I most likely already have it written lol). Can I open a pull request against this repo?

Yes.

**Comment by tyrsson** [comment]
Its 9:22 Chicago (central US time) here. I am trying to not cause us to duplicate work here, so, I will go ahead and review everything tonight that "should not" be impacted by any session changes in the review. Any changes that are relevant to the session handling etc I will address here on Github as it will be relevant to chapter 12. I can see this is not an easy process since the code is split between multiple chapters and a change to one, depending on the change effects all previous chapters... No easy way to accomplish it that I have thought of so far!!

**Comment by fgsl** [comment]
> Its 9:22 Chicago (central US time) here. I am trying to not cause us to duplicate work here, so, I will go ahead and review everything tonight that "should not" be impacted by any session changes in the review. Any changes that are relevant to the session handling etc I will address here on Github as it will be relevant to chapter 12. I can see this is not an easy process since the code is split between multiple chapters and a change to one, depending on the change effects all previous chapters... No easy way to accomplish it that I have thought of so far!!

:)

**Comment by tyrsson** [comment]
Well, I got a preview into the issue, or part of it in the chapter 11 review in the reason that you provide for the logins being different.

> There is a difference for customer registration when it is compared to the previous registrations. The API only allows the customer creation. It is not possible to update or delete a customer. Of course, this is for avoiding that a customer removes another customer or changes the personal data of another customer

This should be handled with an Assertion based on a non ambiguous user identifier such as a auto incremented user id. At the moment a user is authenticated you know their Id. As long as that id never changes when you allow them to modify their account, you only assert the permission to do so if the state exist that their user id and that of the account to be edited has the same id. Otherwise, no assertion takes place, condition fails, account can not be edited.

Furthermore, I usually only show them the link to edit their own account, and in the access check for that particular action I check then, so that if there is no access the user is redirected and the attempt is logged as a 403 as it can give clues if someone is attempting to gain access to the software you build or another users account. The hard part is when a malicious user has an account but attempts access as a guest, which is why its very helpful to have a related table to store IP's from successful logins, because once stored; it can be queried against in the case that some guest performs more than n number of 403 flagged attempts. This does not actually identify the malicious user, but it certainly provides very useful data in the event that the malicious user does not make sure they are using a different IP before the probing starts.

As soon as I have a chance to finish the chapter 11 review I will look into chapter 12 and see if I can connect all the dots in regards to this topic of discussion. I just wanted to post my thoughts on it as the information becomes available from my perspective so I do not forget to come back to it.

**Comment by tyrsson** [comment]
OK, I have read the relevant parts of chapter 12.

The additional context is not needed. You are already using the RBAC. Your user is already authenticated. Authentication here is NOT the component to use for allowing ACCESS to one module or the other. 

A user authenticates ONCE, regardless of what backend service is queried for verification of that. Once authenticated the user is then either granted access to part of the domain model or they are not. 

Your reference to this method being the determining factor:
 public function hasIdentity()
    {
        return ! $this->getStorage()->isEmpty();
    }
The explanation you give within the text is incomplete and incorrect.

You have to be very careful and not take for granted that the container being used for the Authentication Service does not check for who was authenticated. It does, how else could it return the identity? The method you cite in the text actually proxies to this method. See Laminas/Authentication/Storage/Session which is what is returned by $this->getStorage() in the method you cite.
    public function isEmpty()
    {
        return ! isset($this->session->{$this->member});
    }

The authentication service storage session implements the authentication storage interface and uses a session container internally. It writes the identity column passed to the adapter into the container as a key, ie property (depending on the flags and since its parent context is initialized with ArrayObject::ARRAY_AS_PROPS) it can be accessed as a class property.

The system should set a default role to an account created through standard registration. 
User, standard_user, whatever. They should not have permission to access anything other than purchasing.
Users that can access any other area should be assigned the role of employee and have permissions that allow them certain elevated privileges, such as creating products, which would then in turn modify the inventory etc.
The only session data that should be used for this process is the identity column that is stored by the authentication service, no other data should need be stored in the session for authorization purposes. That means once per request you have to query for the users authorization data, once and only once, which could be part of a join with other tables to provide the authenticated users "context". This insures that any modification to that data is realized in real time on the next request.

If it must be stored, in VERY high request per second implementations then there is a couple choices. I would suggest caching it, since, which then lends itself better to testing environments than when using data stored in the session since sessions are not usually initialized via cli. Either way, when the user is modified by another user, with privilege to change their privileges, ie a manager or admin, to assign an employee role, or an employee to modify account info, or order info for a standard user, but should not allow the modification of roles. Sorry I digressed there. when the user is modified then either the cache must be invalidated or the current users session that is being modified must be killed and the user forced to log back in. If not then their data is stale. I can think of many situations where just a single request completion could result in a site owner being locked out. If the malicious user obtains enough environmental information (ie from their co-workers) about what is about to happen. The delete user screen happens to open, Bob sticks his head in the door and mentions to Mr Bad Guy that he just overheard whathisname mention that Mr Bad Guy is getting canned. At that moment, all it takes is a single click to remove the owners account if its not protected via an assertion and prevented from being modified by anyone that is not the account owner.

As a side note. In the code block I included earlier is the key to session invalidation, because you have the container name, since you do not pass a custom container name when the authentication service is created, the component will create the default container which is Laminas_Auth, the target member will be whatever db column name you pass (its value that is returned from the auth query that is) as the identity argument when the authentication adapter is created and its context setup for use.

**Comment by fgsl** [comment]
* The authentication remains separated to each module. There is not intention to create a single sign-on or similar.
* Previously, it was made a change for creating an IdentityManager class. In Chapter 12 this class served to show how to set different namespaces for authentication sessions. This was a good contribution. The inherited identity management class for Inventory module is more aggressive with permissions checking now. In future, it can serve as an optimization case study.
* This discussion can serve as requirement for a new component. It could be part of https://github.com/fgsl/framework. If it is a really required and generic feature, it must be addressed to Laminas.
* That's all folks. 

Related issues:
* https://github.com/PacktPublishing/Laminas-Web-Development/issues/69
* https://github.com/PacktPublishing/Laminas-Web-Development/issues/62
* https://github.com/PacktPublishing/Laminas-Web-Development/issues/60
* https://github.com/PacktPublishing/Laminas-Web-Development/issues/59
* https://github.com/PacktPublishing/Laminas-Web-Development/issues/58
