### ISSUE TITLE
Chapter 11 OrderItem Model

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#51]
Following issues

- Missing declare
- Unused use statements:
use Laminas\Validator\EmailAddress;
use Laminas\Filter\StringToUpper;
use Laminas\Validator\ValidatorChain;
use Laminas\Validator\StringLength;
use Laminas\I18n\Filter\Alnum;

- Missing return types for methods:
exchangeArray
toArray

- White space at the ends of lines 57, 68
- Redundant parenthesis in every line of exchangArray body
- Missing blank line after class body closing brace

**Comment by fgsl** [comment]
What was done:

- Missing declare (OK)
- Unused use statements:
use Laminas\Validator\EmailAddress; (OK)
use Laminas\Filter\StringToUpper; (OK)
use Laminas\Validator\ValidatorChain; (OK)
use Laminas\Validator\StringLength; (OK)
use Laminas\I18n\Filter\Alnum; (OK)

- Missing return types for methods:
exchangeArray (OK)
toArray (NO)

- White space at the ends of lines 57, 68 (OK)
- Redundant parenthesis in every line of exchangArray body (NO)
- Missing blank line after class body closing brace (NO)

Some issues are stuff to discuss in the improvement of static analysis section.

Pure water has no fishes.
