### ISSUE TITLE
Chapter 11 ProductTable creation context change

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#52]
In the text page 8/33 of chapter 11 we find this quote:

> You can ask why we didn’t we modify ProductTable constructor for receiving two table gateways instead of injecting one of the table gateways with a setter method? We can’t change constructor signature because the constructor is inherited.

This is a perfect use case for a Delegated Service.

https://docs.laminas.dev/laminas-servicemanager/delegators/

However, there is no reason why the constructor can not be overridden. Constructor signatures can change, as long as the parent::__construct($arg, $arg2); whatever the use case may be within that context.

**Comment by fgsl** [comment]
This can be a useful note.
