### ISSUE TITLE
Chapter 11 module.config.php files, all modules

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#53]
The following also applies to all chapter 11 module.config.php files

https://github.com/PacktPublishing/Laminas-Web-Development/blob/e3db64f8d87ef26dff6f86614ebdc655c55d9e85/chapter11/whatstore/module/Inventory/config/module.config.php#L41
Aliases are not needed here.

https://github.com/PacktPublishing/Laminas-Web-Development/blob/e3db64f8d87ef26dff6f86614ebdc655c55d9e85/chapter11/whatstore/module/Inventory/config/module.config.php#L82
Why does every module override this configuration? The only key that should be present in all modules is the template_path_stack option. All other should be in the config file for the module that is responsible for loading the layout template.

https://github.com/PacktPublishing/Laminas-Web-Development/blob/e3db64f8d87ef26dff6f86614ebdc655c55d9e85/chapter11/whatstore/module/Inventory/config/module.config.php#L102
Service Names (identifiers) should use the FQCN::class syntax.

https://github.com/PacktPublishing/Laminas-Web-Development/blob/e3db64f8d87ef26dff6f86614ebdc655c55d9e85/chapter11/whatstore/module/Inventory/config/module.config.php#L113
'view_helpers' key needs removed since the laminas-mvc-form component is now being used.

**Comment by fgsl** [comment]
Added "Removing unnecessary configuration" section, with a refactoring which explains the configuration override and why is not necessary to have all configuration keys for view_manager in each one of the modules.
