### ISSUE TITLE
Identity View Helper

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#54]
https://github.com/PacktPublishing/Laminas-Web-Development/blob/ae4ff3cf796a50c1a2d529cb56b087ff62d0a90d/chapter11/whatstore/module/Store/view/store/index/index.phtml#L12

This component (View Helper Identity) and its usage highlights why the Authentication Service should have a factory. If the factory is provided then the helpers factory queries to discover the Authentication Service that is registered with the service manager. It then injects that service into the helper for usage removing the need to create an instance within the view file.

**Comment by fgsl** [comment]
Solved by https://github.com/PacktPublishing/Laminas-Web-Development/issues/69
