### ISSUE TITLE
Side note about factories and $requestedName

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#56]
This is general, not so much related to the text of the publication.

When relating factory implementations to your students it might be helpful to cover the $requestedName as being the service name within the context of the factory. For many I have noticed that it helps connect the dots for them, especially when they start using Abstract factories where the factory can create any number of instances without previously knowing the service name.
Just thought I would mention it. :)

**Comment by fgsl** [comment]
Thank you very much! :)
