### ISSUE TITLE
Chapter 13 module.config.php

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#64]
The following config keys are NOT needed.

> line: 42
'controller_plugins'
That entire array can be removed.
Line: 69
'view_helpers'
That entire array can be removed as well.

-------------------------------------------------
When you install the flash messenger component using the component installer it will ask you which file you want to inject the component into. You explained this in earlier chapters within this very book.... Why do you think it would not apply to these components? It applies for EXACTLY this reason. Even when not using the component installer. If you install a component, open it. If it has a Module.php in the root directory. Add it to the modules.config.php, or a file that is loaded only for development mode, depending on the use case. If you add it to say config/development.config.php you also need to add it to /config/development.config.dist. Why? Because if you do not add it to the .dist file, then you disable development mode to test something, then go back to development mode then you code will be lost as it will simply copy the contents of the .dist into the .php version of the file.

Also, this topic. Needs to be covered somewhere in the book. The reader getting their heads around this topic is one of the MOST important things in regards to learning how to fast track development in Laminas. If you need to know exactly what autowiring is provided for a component, reading its Module.php and its ConfigProvider classes is THE place to start. If you need to know what service names or aliases are registered for a particular service. Those files are where to find it. If you want to know what the old legacy name for the component was in the latter version of ZendFramework, well, in a lot of cases, those files are where to look. Those two files are what initializes the component within the framework. The reader absolutely has to know of them and their importance in respect to not only the component, but how they allow the framework to use the component and how they can use it within the framework.

Think of it this way. Configuring a Laminas MVC instance does not take place in a single file. It takes place in many files, some which will overwrite the config from previous processing, depending on which file you are speaking of, or the mode of the application. It also does not just happen from .config.php files. Module.php files can also return configuration from many different methods, each with a corresponding interface in the module manager feature namespace or ones that developers register as module manager features and are exposed by their components and will map to a named config key, such as, view_helpers, controllers, etc. Usually they are used to provide a key for organizing the services provided by one of the dedicated plugin managers.

**Comment by fgsl** [comment]
Removed and clarified in chapter.
