### ISSUE TITLE
Should use RenameUpload Filter

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#65]
https://github.com/PacktPublishing/Laminas-Web-Development/blob/b1e6384e2d14c074fee41aeecbe41aba54e31f00/chapter13/tipsandtricks/module/Application/src/Controller/IndexController.php#L64

This really should use the RenameUpload filter so that another trick and best practice example could be combined into one. It allows the hashing of file names as the file is being uploaded.

**Comment by fgsl** [comment]
It was added an explanation in chapter.
